name: 'Comment to PR'
description: 'Comment to a PR with a message. By default, comments if message is not already present.'
inputs:
  repo-token:
    description: Repo token from the action
    required: true
    default: ''
  comment:
    description: 'Text of comment'
    required: true
    default: 'Comment Text'
  exclusive:
    description: 'Whether the comment should be exclusive or not'
    required: false
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
