name: 'Comment to PR'
description: 'Comment to a PR with a message. By default, comments if message is not already present.'
inputs:
  GITHUB_TOKEN:
    description: Repo token from the action
    required: true
    default: ''
  comment:
    description: 'Text of comment'
    required: true
    default: 'Comment Text'
  exclusive:
    description: 'Whether the comment should be exclusive or not'
    required: false
    default: true
  repo_name:
    description: 'Repo name in the format: smartlyio/test-repo. Defaults to current Repo.'
    required: false
    default: ${{ github.repository }}
  pr_number:
    description: 'PR number. Defaults to current PR'
    required: false
    default: ${{ github.event.pull_request.number }}
runs:
  using: 'node20'
  main: 'dist/index.js'
